### ISSUE TITLE
Fix : when user types msg in chat and accidentally  presses enter more than 1 time, the message is sent that many times in chat

### ISSUE THREAD

**Issue by prasadrathod** [Pranav2612000/milaap#158] opened 2020-07-17 05:26 UTC

**Comment by savannahar68** [comment] 2020-07-17 05:53
This issue is because of delay cause after pressing enter.
It broadcasts the message over socket and then clears the chat box.

Simple fix is to clear the message first and then broadcast it.

We'll fix it. Thank you.

**Comment by prasadrathod** [comment] 2020-07-17 06:14
CooL man. You are fast😂.

**Comment by prasadrathod** [comment] 2020-07-17 06:16
I need my reward now😁😁😁😂😂

**Comment by savannahar68** [comment] 2020-07-17 06:53
Steps to repro:

1. Login
2. Enter any room
3. Go to chat section
4. Type message
5. Press on enter - Don't leave enter

Output - Multiple messages will be sent
Expected behaviour - Only one message should be sent

How to fix it: On clicking enter first clear the input box and then broadcast message over socket

@vasusharma7 assigning it to you

**Comment by vasusharma7** [comment] 2020-07-17 09:06
Fixes #162

**Closed** 2020-07-17 11:43 UTC
Labels: bug
